# Generated by Django 4.0.4 on 2022-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to="laptop/<method-wrapper '__str__' of str object at 0x000001F0865669B0>"),
        ),
    ]
