# Generated by Django 4.0.4 on 2022-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_audio_product_battery_product_bluetooth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lan',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sd',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='webcam',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
