# Generated by Django 4.0.4 on 2022-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cd',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sd',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
