# Generated by Django 4.0.4 on 2022-04-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_brand_brand_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_active',
        ),
    ]
