# Generated by Django 4.0.4 on 2022-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_oder_delete_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='list_oder',
            field=models.JSONField(null=True),
        ),
    ]
