# Generated by Django 4.0.4 on 2022-04-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_oder_list_oder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oder',
            name='status_oder',
        ),
    ]
