# Generated by Django 4.0.4 on 2022-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_oder_oder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='oder_status',
            field=models.BooleanField(default=True),
        ),
    ]
