# Generated by Django 4.0.4 on 2022-04-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_oder_oder_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='oder_status',
            new_name='order_status',
        ),
    ]
