# Generated by Django 4.0.4 on 2022-04-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_oder_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='list_oder',
            new_name='list_order',
        ),
    ]
